In [56]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### OECD
https://data.oecd.org/
- "Value added in financial and insurance activities": "DV_VA"
- "General government net lending": "IV_lending"
- "Real effective exchange rates": "C_REER"
- "CPI: all items": "C_cpi"

- "Gross domestic product (output approach)": "C_gdp"

### WB
https://databank.worldbank.org/home.aspx
- "Foreign direct investment, net outflows (% of GDP)": "IV_fdi_outflow"
- "Net trade in goods and services (BoP, current US$)": "IV_trade_balance"
- "Broad money (% of GDP)": "C_M2"

### GDD 
https://www.imf.org/external/datamapper/datasets/GDD
- "nfc_ls"(houshold debt, loans and debt securities, % of GDP): "DV_nfc_ls"
- "hh_ls"(nonfinancial corporate debt, loans and debt securities, % of GDP): "DV_hh_ls"

### Historical Puclic Finance 
https://www.imf.org/external/np/fad/histdb/index.htm
- "exp"(government expenditure, % of GDP): "IV_gov_exp"

### WID
https://wid.world/data/
- "gini": "IV_gini"

In [77]:
# import OECD.csv and select features
oecd = pd.read_csv('data_source/OECD.csv')

oecd = oecd.loc[(oecd['Subject']=='Value added in financial and insurance activities')
                |(oecd['Subject']=='General government net lending')
                |(oecd['Subject']=='Real effective exchange rates')
                |(oecd['Subject']=='CPI: all items')]

oecd = oecd[['Subject','Country','Year','Value']]

In [79]:
# import gdp.csv/OECD
gdp = pd.read_csv('data_source/gdp.csv')
gdp = gdp.loc[gdp['MEASURE']=='VXVOB']
gdp = gdp[['Transaction','Country','Year','Value']]
gdp = gdp.rename(columns={'Transaction':'Subject'})

In [80]:
def wb_clean(df):
    # drop unnecessary columns
    df = df.drop(['Unnamed: 0', 'Country Code', 'Indicator Code', 'V65'], axis=1)
    # change from wide to long format
    df = df.pivot_table(index='Country Name', columns='Indicator Name').unstack().reset_index()
    # rename columns
    df = df.rename(columns={'level_0':'Year', 'Indicator Name':'Subject',
                                       'Country Name':'Country', 0:'Value'})
    convert_dict = {'Year': int, 
                'Value': float
               } 
  
    df = df.astype(convert_dict)
    df['Country'] = df['Country'].str.replace('Russian Federation', 'Russia')
    df['Country'] = df['Country'].str.replace('Korea, Rep.', 'Korea')
    df['Country'] = df['Country'].str.replace('China', "China (People's Republic of)")
    
    return df

In [81]:
fdi_outflow = pd.read_csv('data_source/outflow.csv')
fdi_outflow = wb_clean(fdi_outflow)

trade_balance = pd.read_csv('data_source/netgoodservices.csv')
trade_balance = wb_clean(trade_balance)

m2 = pd.read_csv('data_source/broad_money.csv')
m2 = wb_clean(m2)

<ipython-input-80-1164f411f506>:15: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country'] = df['Country'].str.replace('Korea, Rep.', 'Korea')
<ipython-input-80-1164f411f506>:15: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country'] = df['Country'].str.replace('Korea, Rep.', 'Korea')
<ipython-input-80-1164f411f506>:15: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Country'] = df['Country'].str.replace('Korea, Rep.', 'Korea')

In [82]:
oecd = oecd.append([gdp,fdi_outflow, trade_balance, m2])
oecd = oecd.sort_values(by=['Country', 'Subject', 'Year'])
oecd = oecd.pivot_table(values='Value', index=['Country', 'Year'], columns=['Subject']).reset_index()

In [83]:
gdd = pd.read_csv('data_source/global_debt_database.csv')
gdd = gdd[['country', 'year', 'nfc_ls', 'hh_ls']]

def gdd_clean(df):
    # rename columns
    df = df.rename(columns={'year':'Year', 'country':'Country'})
    # change country name
    df['Country'] = df['Country'].str.replace('Russian Federation', 'Russia')
    df['Country'] = df['Country'].str.replace('Korea, Republic of', 'Korea')
    df['Country'] = df['Country'].str.replace('China, Mainland', "China (People's Republic of)")
    
    # replace 0 with NAs
    df.replace(0, np.nan, inplace=True)
    
    return df
gdd = gdd_clean(gdd)
oecd = pd.merge(oecd, gdd, on=['Country', 'Year'], how='outer')

In [84]:
public_finance = pd.read_csv('data_source/historical_public_finance_dataset.csv')
public_finance = public_finance[['country', 'year', 'exp']]

# clean public_finance dataframe
def public_finance_clean(df):
    # rename columns
    df = df.rename(columns={'year':'Year', 'country':'Country'})
    
    # change country name
    df['Country'] = df['Country'].str.replace('Russian Federation', 'Russia')
    df['Country'] = df['Country'].str.replace('South Korea', 'Korea')
    df['Country'] = df['Country'].str.replace('China', "China (People's Republic of)")
    
    # replace 0 with NAs
    df.replace(0, np.nan, inplace=True)
    
    return df
public_finance = public_finance_clean(public_finance)
oecd = pd.merge(oecd, public_finance, on=['Country', 'Year'], how='outer')

In [85]:
gini = pd.read_csv('data_source/gini.csv')
gini = gini[['V1', 'V4', 'V5']]

def gini_clean(df):
    # rename columns
    df = df.rename(columns={'V4':'Year', 'V1':'Country', 'V5':'gini'})
    
    # change country name
    df['Country'] = df['Country'].str.replace('South Korea', 'Korea')
    df['Country'] = df['Country'].str.replace('China', "China (People's Republic of)")
    
    # replace 0 with NAs
    df.replace(0, np.nan, inplace=True)
    
    return df
gini = gini_clean(gini)
oecd = pd.merge(oecd, gini, on=['Country', 'Year'], how='outer')

In [86]:
oecd = oecd.rename(columns={
    "Value added in financial and insurance activities": "DV_VA",
    "nfc_ls": "DV_nfc_ls",
    "hh_ls": "DV_hh_ls",
    "General government net lending": "IV_lending",
    "exp": "IV_gov_exp",
    "gini": "IV_gini",
    "Net trade in goods and services (BoP, current US$)": "IV_trade_balance",
    "Foreign direct investment, net outflows (% of GDP)": "IV_fdi_outflow",
    "Real effective exchange rates": "C_REER",
    "CPI: all items": "C_cpi",
    "Gross domestic product (output approach)": "C_gdp",
    "Broad money (% of GDP)": "C_M2"
})

In [87]:
oecd.head()

,Country,Year,C_M2,C_cpi,IV_fdi_outflow,IV_lending,C_gdp,IV_trade_balance,C_REER,DV_VA,DV_nfc_ls,DV_hh_ls,IV_gov_exp,IV_gini
0,Afghanistan,1960,13.450412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1961,14.534413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1962,17.195122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1963,14.464496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1964,16.688888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
country_ls = ['Australia', 'Brazil', 'Canada', 'Chile', "China (People's Republic of)", 
            'Denmark', 'Hungary', 'Iceland', 'Israel', 'Japan', 'Korea', 'Mexico', 
            'New Zealand', 'Norway', 'Poland', 'South Africa', 'Sweden', 'Switzerland', 
            'Turkey', 'United Kingdom', 'United States']
oecd = oecd[oecd.Country.isin(country_ls)]

In [89]:
oecd.describe()

,Year,C_M2,C_cpi,IV_fdi_outflow,IV_lending,C_gdp,IV_trade_balance,C_REER,DV_VA,DV_nfc_ls,DV_hh_ls,IV_gov_exp,IV_gini
count,4618.000000,1135.000000,1167.000000,966.000000,546.000000,9.160000e+02,8.990000e+02,898.000000,635.000000,776.000000,792.000000,2414.000000,801.000000
mean,1909.452577,65.124371,21.405610,1.793650,-1.726769,1.347113e+06,-6.763908e+09,123.950507,5.791875,75.465373,49.774606,19.904186,0.474926
std,63.487593,42.857235,136.614265,4.972600,4.287139,2.833417e+06,8.969622e+10,148.648789,2.524193,47.510370,30.654107,15.092522,0.119841
min,1800.000000,8.603164,-3.481539,-43.510564,-13.126368,9.624076e+03,-7.617150e+11,53.010542,1.850994,13.067228,0.084322,0.684444,0.123687
25%,1854.250000,36.316614,2.143572,0.237921,-4.391008,1.726176e+05,-3.547675e+09,91.299922,4.167364,47.252332,27.634867,7.417718,0.392839
50%,1909.000000,54.220514,4.271796,0.879725,-2.147313,3.591655e+05,3.137428e+08,102.571125,5.238788,71.990357,44.733832,15.568450,0.445601
75%,1964.000000,77.539311,9.664251,2.163012,0.539568,1.085692e+06,8.476086e+09,114.791485,6.812228,93.801311,69.540886,30.457950,0.549357
max,2019.000000,252.081567,2947.733000,52.308685,18.671370,1.891509e+07,3.578708e+11,2458.322000,16.074042,569.084027,139.426459,71.841200,0.738630